### ISSUE TITLE
[FEATURE] Welcome message when new member joins the server

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberbot-discord#2]
### Detailed description

When a member joins the server should get a well welcoming message

![image](https://user-images.githubusercontent.com/44284877/194481748-19ec70fe-a0cf-4fba-be1e-92ef7e047f0e.png)

### Context

.

### Possible implementation

If you will have any questions or doubts, let us know.

Thankyou.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Kesav890** [comment]
can i work on this issue?

**Comment by kabir0x23** [comment]
> can i work on this issue?

yes sure
